version: '3'
services:
  my-httpd:

    image: "httpd"
    volumes:
      - "/mnt/wars:/usr/local/apache2/htdocs" 
    ports:
      - "81:80"
    
  my-tomcat:

    image: "tomcat:9"
    volumes:
      - "/mnt/vol-1:/usr/local/tomcat/webapps"
    ports:
      - "8081:8080"    

